# Generated by Django 3.0.5 on 2020-04-10 08:01

import Record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0003_record_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.PositiveIntegerField(choices=[(Record.models.Status['activate'], 1), (Record.models.Status['suspended'], 2)], default=1),
        ),
    ]
